const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "Coding",
    price: 15.99,
    img: "./images/item-1.jpeg",
    info: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "diner double",
    category: "Coding",
    price: 13.99,
    img: "./images/item-2.jpeg",
    info: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "Coding",
    price: 6.99,
    img: "./images/item-3.jpeg",
    info: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "country delight",
    category: "School",
    price: 20.99,
    img: "./images/item-4.jpeg",
    info: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "School",
    price: 22.99,
    img: "./images/item-5.jpeg",
    info: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "School",
    price: 18.99,
    img: "./images/item-6.jpeg",
    info: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "Personal",
    price: 8.99,
    img: "./images/item-7.jpeg",
    info: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "american classic",
    category: "Personal",
    price: 12.99,
    img: "./images/item-8.jpeg",
    info: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "Personal",
    price: 16.99,
    img: "./images/item-9.jpeg",
    info: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
