const menu = [
  {
    id: 1,
    title: "W3 Schools",
    category: "Coding",
    link: "https://www.w3schools.com/",
    desc: `W3Schools is a popular web development platform offering tutorials, references, and exercises related to web technologies such as HTML, CSS, JavaScript, SQL, and more. It provides hands-on guidance for beginners and experienced developers alike, serving as a valuable resource for learning and mastering web development skills.`,
  },
  {
    id: 2,
    title: "ChatGPT",
    category: "Coding",
    link: "https://openai.com/chatgpt/",
    desc: `ChatGPT is a product developed by OpenAI. It is an advanced conversational AI model that can generate human-like text based on the prompts it receives. ChatGPT has a wide range of applications, from answering questions to generating content.`,
  },
  {
    id: 3,
    title: "MDN",
    category: "Coding",
    link: "https://developer.mozilla.org/",
    desc: `MDN Web Docs is a comprehensive resource for web developers provided by Mozilla. It offers documentation, tutorials, and references for various web technologies such as HTML, CSS, JavaScript, and more. Developers often use MDN as a reliable source of information and guidance for web development.`,
  },
  {
    id: 4,
    title: "Google Classroom",
    category: "School",
    link: "https://classroom.google.com/",
    desc: `Google Classroom is a free web service developed by Google for schools and educational institutions. It provides a platform for teachers to create, distribute, and grade assignments, as well as communicate with students. Google Classroom integrates seamlessly with other Google services, making it easier for educators to manage their classes online.`,
  },
  {
    id: 5,
    title: "Canvas",
    category: "School",
    link: "https://www.instructure.com/canvas/",
    desc: `Canvas is a learning management system (LMS) developed by Instructure. It is widely used by educational institutions, including schools, colleges, and universities, to deliver online courses and manage learning resources. Canvas offers features such as course creation, assignment submission, grading, and communication tools for students and instructors.`,
  },
  {
    id: 6,
    title: "Focus",
    category: "School",
    link: "https://graniteschools.focusschoolsoftware.com/focus/",
    desc: `Focus Gradebook is an online tool within the Focus School Software platform that provides teachers with a centralized platform to record, calculate, and manage students' grades effectively.`,
  },
  {
    id: 7,
    title: "Youtube",
    category: "Personal",
    link: "https://www.youtube.com/",
    desc: `YouTube is a popular video-sharing platform owned by Google. Users can upload, view, and share videos on a wide range of topics, including music, entertainment, education, and more. YouTube has become a significant platform for content creators, educators, and businesses to reach a global audience.`,
  },
  {
    id: 8,
    title: "Instagram",
    category: "Personal",
    link: "https://www.instagram.com",
    desc: `Instagram is a social media platform primarily focused on photo and video sharing. Users can upload photos and short videos, apply filters, and share them with their followers or the public. Instagram also offers features such as stories, reels, and IGTV, making it a versatile platform for personal expression, marketing, and content creation.`,
  },
  {
    id: 9,
    title: "Facebook",
    category: "Personal",
    link: "https://www.facebook.com/",
    desc: `Facebook is a leading social media platform founded by Mark Zuckerberg. It allows users to connect with friends, family, and communities, share updates, photos, videos, and engage with content from various sources. Facebook has evolved into a multifaceted platform offering features such as groups, marketplace, events, and advertising solutions for businesses.`,
  },
];
export default menu;
